### ISSUE TITLE
lock on language selection and acceptance of terms

### ISSUE THREAD

**Issue by javivaz** [coskundeniz/ad_clicker#17] opened 2023-04-26 08:22 UTC
The first time the browser window is opened, the language selector appears and stays there without completing any other action. Below the language selector, the acceptance of the default browser terms appears in any incognito window. 
After a few seconds without action, it closes and returns a message that no results were found.

**Comment by coskundeniz** [comment] 2023-04-27 09:27
@javivaz I couldn't reproduce it on my local. Can you give more details and maybe also a recording? Please send the adclicker.log file too. Thank you.

**Comment by ebulku** [comment] 2023-04-27 19:44
Yes this is happening sometimes, based also on the size of the window, and not recognizing the buttons at the end of the modal. We have to add another scroll at the bottom of the modal I think.

![image](https://user-images.githubusercontent.com/11932725/234974171-67c77e1e-4d9b-4219-a60b-818b7717ca55.png)

**Comment by javivaz** [comment] 2023-04-27 22:10
Sorry, I didn't see your message. Indeed, it seems that something has changed. It is not frequent but it does happen sometimes. Thank you for your attention

**Comment by furkankadioglu** [comment] 2023-04-28 01:21
Hey @coskundeniz 
Here is my adclicker.log, I have same issue.

```
I28-04-2023 02:19:53 [DEBUG] utils.py:166: Installed Chrome version: 112
28-04-2023 02:19:58 [ INFO] search_controller.py: 68: Starting search for 'wireless keyboard'
28-04-2023 02:20:10 [ERROR] search_controller.py: 94: Timed out waiting for results!
28-04-2023 02:20:10 [ INFO] ad_clicker.py: 88: No ads in the search results!

```

**Comment by coskundeniz** [comment] 2023-04-28 09:17
> Yes this is happening sometimes, based also on the size of the window, and not recognizing the buttons at the end of the modal. We have to add another scroll at the bottom of the modal I think.
> 
> ![image](https://user-images.githubusercontent.com/11932725/234974171-67c77e1e-4d9b-4219-a60b-818b7717ca55.png)

I also tried by decreasing the browser window size but still cannot reproduce. I will take a look if I see it during my runs.

**Comment by furkankadioglu** [comment] 2023-04-29 01:18
It might be related with OS Language / Geolocation. I using English language with Turkish Keyboard and my location is Portugal. Not sure but looks like related. @coskundeniz

**Comment by furkankadioglu** [comment] 2023-04-29 02:33
@coskundeniz 

Well, after few tests with VPN now I pretty sure. When I enable my Turkish VPN this modal disappearing. So you should try to reproduce with another language or with a VPN. 

And one more thing, there is another issue. When I run it after first ad visit browser is crashing.
![Screen Shot 2023-04-29 at 03 29 36](https://user-images.githubusercontent.com/5060068/235279621-b8cc0208-6b38-4ed0-a5ca-faaeaad5e5b2.png)

Thanks for this perfect project mate.

**Comment by coskundeniz** [comment] 2023-04-29 16:05
Should be fixed with the latest version.

**Closed as completed by coskundeniz** 2023-04-29 16:05 UTC

**Comment by coskundeniz** [comment] 2023-04-29 16:07
> @coskundeniz
> 
> Well, after few tests with VPN now I pretty sure. When I enable my Turkish VPN this modal disappearing. So you should try to reproduce with another language or with a VPN.
> 
> And one more thing, there is another issue. When I run it after first ad visit browser is crashing. ![Screen Shot 2023-04-29 at 03 29 36](https://user-images.githubusercontent.com/5060068/235279621-b8cc0208-6b38-4ed0-a5ca-faaeaad5e5b2.png)
> 
> Thanks for this perfect project mate.

Thank you for the advise. I was able to reproduce by using a proxy from Switzerland. If crash issue is reproducible, you can create a separate issue for it.
